import path from 'path';
import fs from 'fs-extra';
import { Plugin, PluginContext } from '../core/plugin';

export const swaggerPlugin: Plugin = {
  name: 'swagger',
  dependencies: {}, // Assigned dynamically
  devDependencies: {},
  execute: async (context: PluginContext) => {
    const { targetDir, config } = context;

    if (config.framework === 'express') {
      context.dependencies = {
        'swagger-ui-express': '^5.0.0',
        'swagger-jsdoc': '^6.2.8',
      };
      context.devDependencies = {
        '@types/swagger-ui-express': '^4.1.6',
        '@types/swagger-jsdoc': '^6.0.4',
      };

      let configDir = path.join(targetDir, 'src', 'config');
      await fs.ensureDir(configDir);
      
      await fs.writeFile(path.join(configDir, 'swagger.ts'), `import swaggerJsdoc from 'swagger-jsdoc';

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: '${config.name} API',
      version: '1.0.0',
      description: 'API documentation generated by DevForge',
    },
    servers: [{ url: 'http://localhost:3000', description: 'Development server' }],
  },
  apis: ['./src/routes/*.ts', './src/modules/**/*.routes.ts', './src/controllers/*.ts', './src/modules/**/*.controller.ts'],
};

export const swaggerSpec = swaggerJsdoc(options);
`);

      const appTsPath = path.join(targetDir, 'src', 'app.ts');
      let appTsContent = await fs.readFile(appTsPath, 'utf-8');
      appTsContent = appTsContent.replace('// PLUGINS_IMPORT', `// PLUGINS_IMPORT\nimport swaggerUi from 'swagger-ui-express';\nimport { swaggerSpec } from './config/swagger';`);
      appTsContent = appTsContent.replace('// PLUGINS_INIT', `// PLUGINS_INIT\napp.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));`);
      await fs.writeFile(appTsPath, appTsContent);

    } else if (config.framework === 'fastify') {
      context.dependencies = {
        '@fastify/swagger': '^8.14.0',
        '@fastify/swagger-ui': '^3.0.0',
      };

      const appTsPath = path.join(targetDir, 'src', 'app.ts');
      let appTsContent = await fs.readFile(appTsPath, 'utf-8');
      appTsContent = appTsContent.replace('// PLUGINS_IMPORT', `// PLUGINS_IMPORT\nimport swagger from '@fastify/swagger';\nimport swaggerUi from '@fastify/swagger-ui';`);
      appTsContent = appTsContent.replace('// PLUGINS_INIT', `// PLUGINS_INIT\napp.register(swagger, {\n  openapi: {\n    info: {\n      title: '${config.name} API',\n      version: '1.0.0'\n    }\n  }\n});\n\napp.register(swaggerUi, {\n  routePrefix: '/api-docs',\n});`);
      await fs.writeFile(appTsPath, appTsContent);
    }
  }
};
